name: phm_knowledge
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - jupyter
  - notebook
  - ipykernel
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - pip:
    - langchain==0.3.27
    - langchain-community==0.3.31
    - langchain-core==0.3.79
    - langchain-openai==0.3.35
    - langchain-text-splitters==0.3.11
    - chromadb==1.1.1
    - faiss-cpu==1.12.0
    - openai==2.3.0
    - pyyaml>=6.0
    - tqdm>=4.65.0
    - python-dotenv>=1.0.0
